version: '3'

volumes:
  keycloak-db-data:
    driver: local

services:
  keycloak:
    build: .
    container_name: custom-auth-service
    environment:
      #Admin Credentials
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: MyKeycloak493
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: MyKeycloak493
      KC_DB_URL: 'jdbc:postgresql://db.buwvyjjfiyfcgcdvbfke.supabase.co:5432/postgres'
      KC_DB_USERNAME: 'postgres'
      KC_DB_PASSWORD: 'Skyliner005!"£'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: 0.0.0.0
      PROXY_ADDRESS_FORWARDING: "true"
      KC_SPI_THEME_DEFAULT: 'my-theme'
    command:
      - "-v start --optimized
      "
    ports:
      - 8443:8443
      - 8080:8080
